opst_root/urls.py
from django.conf.urls import *
# from cms.sitemaps import CMSSitemap
from django.views.generic import TemplateView

urlpatterns = patterns('opst_root.views',
	url(r'^affichage/(?P<slug>[a-zA-Z0-9_.-]+)/$', 'affichage_ressource'),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# from cms.sitemaps import CMSSitemap

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^opst_root/', include('opst_root.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/tagging/autocomplete', include('pagetags.urls')),
    url(r'^', include('cms.urls')),
)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
		(r'^static/(?P<path>.*)$', 'django.views.static.serve',                                                     
		{'document_root': settings.STATIC_ROOT}),
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns # + staticfiles_urlpatterns()

opst_plugins/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.template.defaultfilters import slugify
from cms.models import CMSPlugin


class TagCloudPluginModel(CMSPlugin):

    result_page = models.ForeignKey('cms.Page', related_name='opst_plugin_tagcloud')
    items_min = models.PositiveIntegerField(default=3)


class SearchBoxPluginModel(CMSPlugin):

    result_page = models.ForeignKey('cms.Page', related_name='opst_plugin_searchbox')

class NewsFeedEntry(models.Model):

    title            = models.CharField(max_length=128)
    url              = models.URLField()
    publication_date = models.DateTimeField(blank=True, null=True)

    def __unicode__(self): return self.title
	
class NewsFeedPluginModel(CMSPlugin):

    title    = models.CharField(max_length=128)
    list_max = models.PositiveIntegerField(default=8)
    news     = models.ManyToManyField(NewsFeedEntry)


class NewsFeedExtPluginModel(CMSPlugin):

    title    = models.CharField(max_length=128)
    list_max = models.PositiveIntegerField(default=8)
    url      = models.URLField(max_length=1024)


class NewsFeedPagePluginModel(CMSPlugin):

    title       = models.CharField(max_length=128)
    list_max    = models.PositiveIntegerField(default=8)
    url         = models.URLField(max_length=1024)
    update_last = models.DateTimeField(blank=True, null=True)
    pages       = models.ManyToManyField('cms.Page', blank=True, null=True)
    parent_page = models.ForeignKey('cms.Page', blank=True, null=True, related_name='parent_of_newsfeed')

    def update(self):

        import feedparser

        from time import mktime
        from datetime import datetime
        from slugify import slugify

        from django.contrib.sites.models import Site

        from cms.models import Page, Title
        from cms.plugins.text.models import Text

        try: p_last = self.pages.latest('publication_date')
        except Page.DoesNotExist: p_last = None

        try:

            for e in feedparser.parse(self.url)['entries']:

                date  = e.get('published_parsed')
                title = e.get('title')
                body  = e.get('summary')
                url   = e.get('link')

                if date and title and body:

                    date = datetime.fromtimestamp(mktime(date))

                    if p_last and date <= p_last.publication_date: continue

                    p=Page(site=Site.objects.all()[0], in_navigation=False, published=True, template='page-full.html')
                    p.publication_date = date

                    if self.parent_page: p.parent = self.parent_page
            
                    p.save()

                    self.pages.add(p)
                    self.save()

                    t=Title(language='en', title=title, slug='%s-%s' % (slugify(title), p.pk), page=p)
                    t.save()
        
                    pl=p.placeholders.get(slot='page')

                    if url: body = u'%s<p><a href="%s">Lire la suite de l\'article…</a></p>' % (body, url)
                    txt=Text(body=body, language='en', plugin_type='TextPlugin')
                    txt.save()

                    pl.cmsplugin_set.add(txt)
                    pl.save()

        except: pass

        self.update_last = datetime.now()
        self.save()
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.

class Auteur(models.Model):
    id = models.IntegerField(primary_key=True)
    nom = models.CharField(max_length=90)
    prenom = models.CharField(max_length=90)
    def __unicode__(self):
        return self.nom + ' ' + self.prenom 
    
    class Meta:
        db_table = u'auteur'

class Categorie(models.Model):
    id = models.IntegerField(primary_key=True)
    nom = models.CharField(max_length=120)
    slug = models.SlugField(max_length=150)
    def __unicode__(self):
        return self.nom
    class Meta:
        db_table = u'categorie'

class Revue(models.Model):
    id = models.IntegerField(primary_key=True)
    nom = models.CharField(max_length=600)
    nb_num_revues = models.IntegerField(null=True, blank=True, verbose_name="Nombre de numéros de revues")
    def __unicode__(self):
        return self.nom
    class Meta:
        db_table = u'revue'

class Tag(models.Model):
    id = models.IntegerField(primary_key=True)
    nom = models.CharField(max_length=120)
    slug = models.SlugField(max_length=150)
    def __unicode__(self):
        return self.nom
    def nb_tags(self):
        return self.items.count()
    nb_tags.short_description = 'Nombre d\'utilisations du tag'
    class Meta:
        db_table = u'tag'	
	
class Ressource(models.Model):
    id = models.IntegerField(primary_key=True)
    titre = models.CharField(max_length=900)
    slug = models.SlugField(max_length=900, blank=True)
    texte = models.TextField(blank=True)
    lien_texte = models.CharField(max_length=1800, blank=True)
    annee = models.IntegerField()
    mois = models.CharField(max_length=30, blank=True)
    lieu = models.CharField(max_length=300, blank=True)
    page_deb = models.IntegerField(null=True, blank=True, verbose_name='Page de début')
    page_fin = models.IntegerField(null=True, blank=True, verbose_name='Page de fin')
    date_debut = models.DateField(null=True, blank=True, verbose_name='Date de début')
    date_fin = models.DateField(null=True, blank=True, verbose_name='Date de fin')
    editeur = models.CharField(max_length=450, blank=True)
    formation = models.CharField(max_length=300, blank=True)
    universite = models.CharField(max_length=300, blank=True, verbose_name='Université')
    discipline = models.CharField(max_length=300, blank=True)
    type_production = models.CharField(max_length=900, blank=True)
    type_rapport = models.CharField(max_length=900, blank=True)
    id_revue = models.ForeignKey(Revue, db_column='id_revue', verbose_name= 'Nom de la revue attribuée', null=True, blank=True)
    tags = models.ManyToManyField(Tag)
    auteurs = models.ManyToManyField(Auteur)
    ordering = ['-annee']
    def __unicode__(self):
        return self.titre
    class Meta:
        db_table = u'ressource'

class SousCategorie(models.Model):
    id = models.IntegerField(primary_key=True)
    nom = models.CharField(max_length=120)
    slug = models.SlugField(max_length=150, blank=True)
    def __unicode__(self):
        return self.nom
    class Meta:
        db_table = u'sous_categorie'

class RessourceCatSsCat(models.Model):
    id = models.IntegerField(primary_key=True)
    id_ressource = models.ForeignKey(Ressource, db_column='id_ressource', verbose_name='Ressource')
    id_categorie = models.ForeignKey(Categorie, db_column='id_categorie', verbose_name='Catégorie')
    id_sous_cat = models.ForeignKey(SousCategorie, db_column='id_sous_cat', verbose_name='Sous-Catégorie')
    def __unicode__(self):
        return u"{} à {}/{}".format(self.id_ressource.titre, self.id_categorie.nom, self.id_sous_cat.nom)
    class Meta:
        db_table = u'ressource_cat_ss_cat'
        verbose_name = 'Ressources - Categories - Sous-Catégories'

class RessourcePluginModel(CMSPlugin):
    ressource = models.ForeignKey(Ressource, verbose_name='Ressource')
    categorie = models.ForeignKey(Categorie, verbose_name='Catégorie')
    sous_categorie = models.ForeignKey(SousCategorie, verbose_name='Sous-Catégorie')

class MultipleSearchBoxPluginModel(CMSPlugin):
	
    result_page = models.ForeignKey('cms.Page', related_name="opst_plugin_multiplesearchbox")

opst_root/models.py
from django.db import models

opst_root/views.py
# Create your views here.
# -*- coding:utf-8 -*-
from django.http import HttpResponseRedirect, HttpResponse
from opst_plugins.models import Ressource, Categorie
from django.template import *
from django.shortcuts import render
from django.utils import timezone
from define import *

def affichage_ressource(request, slug):
	""" Affiche une ressource complete comprenant
		les tags, les auteurs, les categories """
	edit = request.GET.get('edit')
	# Récupération de la ressource
	ressource = Ressource.objects.get(slug=slug)
	# Récupération de la revue
	try:
		revue = Revue.objects.get(id=ressource.id_revue.id)
	except AttributeError:
		pass
	# Récupération des auteurs
	auteurs = ressource.auteurs.all()
	# Récupération des tags
	tags = ressource.tags.all()
	# Récupération des cats
	cats_ss_cats = Categorie.objects.filter(ressourcecatsscat__id_ressource=ressource.id)
	return render(request, 'recherche/affichage_page.html', locals())

opst_root/templates/opst_root/breadcrumbs.html
{% for ance in ancestors %}
<ul{% if forloop.first %} id="breadcrumbs"{% endif %}><li>{% if not forloop.last %}<a href="{{ ance.get_absolute_url }}">{{ ance.get_menu_title }}</a>{% else %}{{ ance.get_menu_title }}{% endif %}</li>
{% endfor %}
{% for ance in ancestors %}
</ul>
{% endfor %}

opst_root/templates/opst_root/date.html
{{ une_date }}

opst_root/templates/opst_root/detail.html
<h1>{{ revue.nom }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url opst_root.views.vote revue.id %}" method="post">
{% csrf_token %}
{% for ressource in revue.ressource_set.all %}
    <input type="radio" name="ressource" id="ressource{{ forloop.counter }}" value="{{ ressource.id }}" />
    <label for="ressource{{ forloop.counter }}">{{ ressource.titre }}</label><br/>
{% endfor %}
<input type="submit" value="Vote" />
</form>

opst_root/templates/opst_root/home.html
{% extends "main.html" %}

{% load cms_tags %}

{% block main %}

<div class="yui3-g">

    <div id="col-left" class="yui3-u-1-5">
        {% placeholder "left" %}
    </div>

    <div class="yui3-u-3-5">
        <div id="une" class="page">{% placeholder "page" %}</div>
        <div id="second" class="page">{% placeholder "second" %}</div>
    </div>

    <div id="col-right" class="yui3-u-1-5">
        {% placeholder "right" %}
    </div>

</div>

{% endblock %}

opst_root/templates/opst_root/index.html
{% if latest_revue_list %}
    <ul>
    {% for revue in latest_revue_list %}
        <li><a href="{% url opst_root.views.revue revue.id %}">{{ revue.nom }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No revues are available.</p>
{% endif %}

opst_root/templates/opst_root/main.html
{% load cms_tags sekizai_tags menu_tags page_tags %}
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>OPSN - {{ request.current_page.get_title }}</title>
    <meta name="keywords" content="{{ request.current_page.pagetagging.page_tags }}" />
    <link rel="icon" type="image/png" href="{% static "style/logo_128.png" %}" />
    {% render_block "css" %}
{% addtoblock "css" %}
    <link rel="stylesheet" type="text/css" href="{% static "style/yui3-fonts-reset-grids-base-combo-min.css" %}" media="all" />
    <link rel="stylesheet" type="text/css" href="{% static "style/style.css" %}" media="all" />
    <link rel="stylesheet" type="text/css" href="{% static "style/stylesheet.css" %}" media="all" />
{% endaddtoblock %}
</head>

<body>

<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["trackPageView"]);
  _paq.push(["enableLinkTracking"]);

  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "://opst.tetaneutral.net/piwik/";
    _paq.push(["setTrackerUrl", u+"piwik.php"]);
    _paq.push(["setSiteId", "1"]);
    var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
    g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->

    {% cms_toolbar %}
    {% render_block "js" %}
    
<div id="header">
    <a id="home" href="/"></a>
</div>

<ul id="menu">
    {% show_menu 0 0 %}
</ul>

<div id="main">
    {% block main %}{% endblock %}
</div>

<div id="footer">
{% pages_with_tags 'footer' order alphabetical as page_list %}
{% for p in page_list %}
    <a href="{{ p.get_absolute_url }}">{{ p.get_title }}</a>
{% endfor %}
</div>

</body>
</html>

opst_root/templates/opst_root/page-full.html
{% extends "main.html" %}

{% load cms_tags %}

{% block main %}

<div class="page">

<h1>{{ request.current_page.get_title }}</h1>

{% placeholder "page" %}

</div>

{% endblock %}

opst_root/templates/opst_root/page-left.html
{% extends "main.html" %}

{% load cms_tags menu_tags %}

{% block main %}

<div class="yui3-g">

    <div id="col-left" class="yui3-u-1-5">
        {% placeholder "left" %}
    </div>

    <div class="yui3-u-3-5 page">
        <h1>{{ request.current_page.get_title }}</h1>
{% placeholder "page" %}
    </div>

    <div id="col-right" class="yui3-u-1-5">
        {% placeholder "right" %}
    </div>

</div>

{% endblock %}

opst_root/templates/opst_root/page.html
{% extends "main.html" %}

{% load cms_tags menu_tags %}

{% block main %}

<div class="yui3-g">

    <div id="col-left" class="yui3-u-1-5">
{% show_breadcrumb 1 "breadcrumbs.html" %}
{% if request.current_page.children.count %}<ul id="page-children">{% show_sub_menu 1 %}</ul>{% endif %}
    </div>

    <div class="yui3-u-3-5 page">
        <h1>{{ request.current_page.get_title }}</h1>
{% placeholder "page" %}
    </div>

    <div id="col-right" class="yui3-u-1-5">
        {% placeholder "right" %}
    </div>

</div>

{% endblock %}

opst_root/templates/opst_root/res.html
<html>
	<head>
		<title> {{ressource.titre}} </title>
	</head>
	<h3>
	{% if ressource.texte %}
		{{ressource.texte}} <br/>
	{% else %}
		pas de texte pour cette ressource <br/>
	{% endif %}
	</h3>
	{{ressource.annee}}
</html>

opst_root/templates/opst_root/results.html
<h1>{{ revue.nom }}</h1>

{{ ressource.titre }} <br/><br/>

<a href="{% url opst_root.views.revue revue.id %}">Vote again?</a>

opst_root/templates/opst_root/test.html
{% extends "page.html" %}

{{ request.current_page.get_title }}