urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# from cms.sitemaps import CMSSitemap

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^opst_root/', include('opst_root.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/tagging/autocomplete', include('pagetags.urls')),
    url(r'^', include('cms.urls')),
)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
		(r'^static/(?P<path>.*)$', 'django.views.static.serve',                                                     
		{'document_root': settings.STATIC_ROOT}),
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns # + staticfiles_urlpatterns()

opst_plugins/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.template.defaultfilters import slugify
from cms.models import CMSPlugin


class TagCloudPluginModel(CMSPlugin):

    result_page = models.ForeignKey('cms.Page', related_name='opst_plugin_tagcloud')
    items_min = models.PositiveIntegerField(default=3)


class SearchBoxPluginModel(CMSPlugin):

    result_page = models.ForeignKey('cms.Page', related_name='opst_plugin_searchbox')

class NewsFeedEntry(models.Model):

    title            = models.CharField(max_length=128)
    url              = models.URLField()
    publication_date = models.DateTimeField(blank=True, null=True)

    def __unicode__(self): return self.title
	
class NewsFeedPluginModel(CMSPlugin):

    title    = models.CharField(max_length=128)
    list_max = models.PositiveIntegerField(default=8)
    news     = models.ManyToManyField(NewsFeedEntry)


class NewsFeedExtPluginModel(CMSPlugin):

    title    = models.CharField(max_length=128)
    list_max = models.PositiveIntegerField(default=8)
    url      = models.URLField(max_length=1024)


class NewsFeedPagePluginModel(CMSPlugin):

    title       = models.CharField(max_length=128)
    list_max    = models.PositiveIntegerField(default=8)
    url         = models.URLField(max_length=1024)
    update_last = models.DateTimeField(blank=True, null=True)
    pages       = models.ManyToManyField('cms.Page', blank=True, null=True)
    parent_page = models.ForeignKey('cms.Page', blank=True, null=True, related_name='parent_of_newsfeed')

    def update(self):

        import feedparser

        from time import mktime
        from datetime import datetime
        from slugify import slugify

        from django.contrib.sites.models import Site

        from cms.models import Page, Title
        from cms.plugins.text.models import Text

        try: p_last = self.pages.latest('publication_date')
        except Page.DoesNotExist: p_last = None

        try:

            for e in feedparser.parse(self.url)['entries']:

                date  = e.get('published_parsed')
                title = e.get('title')
                body  = e.get('summary')
                url   = e.get('link')

                if date and title and body:

                    date = datetime.fromtimestamp(mktime(date))

                    if p_last and date <= p_last.publication_date: continue

                    p=Page(site=Site.objects.all()[0], in_navigation=False, published=True, template='page-full.html')
                    p.publication_date = date

                    if self.parent_page: p.parent = self.parent_page
            
                    p.save()

                    self.pages.add(p)
                    self.save()

                    t=Title(language='en', title=title, slug='%s-%s' % (slugify(title), p.pk), page=p)
                    t.save()
        
                    pl=p.placeholders.get(slot='page')

                    if url: body = u'%s<p><a href="%s">Lire la suite de l\'article…</a></p>' % (body, url)
                    txt=Text(body=body, language='en', plugin_type='TextPlugin')
                    txt.save()

                    pl.cmsplugin_set.add(txt)
                    pl.save()

        except: pass

        self.update_last = datetime.now()
        self.save()
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.

class Auteur(models.Model):
    id = models.IntegerField(primary_key=True)
    nom = models.CharField(max_length=90)
    prenom = models.CharField(max_length=90)
    def __unicode__(self):
        return self.nom + ' ' + self.prenom 
    
    class Meta:
        db_table = u'auteur'

class Categorie(models.Model):
    id = models.IntegerField(primary_key=True)
    nom = models.CharField(max_length=120)
    slug = models.SlugField(max_length=150)
    def __unicode__(self):
        return self.nom
    class Meta:
        db_table = u'categorie'

class Revue(models.Model):
    id = models.IntegerField(primary_key=True)
    nom = models.CharField(max_length=600)
    nb_num_revues = models.IntegerField(null=True, blank=True, verbose_name="Nombre de numéros de revues")
    def __unicode__(self):
        return self.nom
    class Meta:
        db_table = u'revue'

class Tag(models.Model):
    id = models.IntegerField(primary_key=True)
    nom = models.CharField(max_length=120)
    slug = models.SlugField(max_length=150)
    def __unicode__(self):
        return self.nom
    def nb_tags(self):
        return self.items.count()
    nb_tags.short_description = 'Nombre d\'utilisations du tag'
    class Meta:
        db_table = u'tag'	
	
class Ressource(models.Model):
    id = models.IntegerField(primary_key=True)
    titre = models.CharField(max_length=900)
    slug = models.SlugField(max_length=900, blank=True)
    texte = models.TextField(blank=True)
    lien_texte = models.CharField(max_length=1800, blank=True)
    annee = models.IntegerField()
    mois = models.CharField(max_length=30, blank=True)
    lieu = models.CharField(max_length=300, blank=True)
    page_deb = models.IntegerField(null=True, blank=True, verbose_name='Page de début')
    page_fin = models.IntegerField(null=True, blank=True, verbose_name='Page de fin')
    date_debut = models.DateField(null=True, blank=True, verbose_name='Date de début')
    date_fin = models.DateField(null=True, blank=True, verbose_name='Date de fin')
    editeur = models.CharField(max_length=450, blank=True)
    formation = models.CharField(max_length=300, blank=True)
    universite = models.CharField(max_length=300, blank=True, verbose_name='Université')
    discipline = models.CharField(max_length=300, blank=True)
    type_production = models.CharField(max_length=900, blank=True)
    type_rapport = models.CharField(max_length=900, blank=True)
    id_revue = models.ForeignKey(Revue, db_column='id_revue', verbose_name= 'Nom de la revue attribuée', null=True, blank=True)
    tags = models.ManyToManyField(Tag)
    auteurs = models.ManyToManyField(Auteur)
    ordering = ['-annee']
    def __unicode__(self):
        return self.titre
    class Meta:
        db_table = u'ressource'

class SousCategorie(models.Model):
    id = models.IntegerField(primary_key=True)
    nom = models.CharField(max_length=120)
    slug = models.SlugField(max_length=150, blank=True)
    def __unicode__(self):
        return self.nom
    class Meta:
        db_table = u'sous_categorie'

class RessourceCatSsCat(models.Model):
    id = models.IntegerField(primary_key=True)
    id_ressource = models.ForeignKey(Ressource, db_column='id_ressource', verbose_name='Ressource')
    id_categorie = models.ForeignKey(Categorie, db_column='id_categorie', verbose_name='Catégorie')
    id_sous_cat = models.ForeignKey(SousCategorie, db_column='id_sous_cat', verbose_name='Sous-Catégorie')
    def __unicode__(self):
        return u"{} à {}/{}".format(self.id_ressource.titre, self.id_categorie.nom, self.id_sous_cat.nom)
    class Meta:
        db_table = u'ressource_cat_ss_cat'
        verbose_name = 'Ressources - Categories - Sous-Catégories'

class RessourcePluginModel(CMSPlugin):
    ressource = models.ForeignKey(Ressource, verbose_name='Ressource')
    categorie = models.ForeignKey(Categorie, verbose_name='Catégorie')
    sous_categorie = models.ForeignKey(SousCategorie, verbose_name='Sous-Catégorie')

class MultipleSearchBoxPluginModel(CMSPlugin):
	
    result_page = models.ForeignKey('cms.Page', related_name="opst_plugin_multiplesearchbox")

opst_plugins/forms.py
# -*- coding:utf-8 -*-
from django import forms
from .data import *

# Formulaire de recherche simple heritant de la classe Form du module forms
class SearchBoxForm(forms.Form):
	# On instancie un champs chaine de caracteres dans la variable q
    q = forms.CharField(max_length=128)
	
# Formulaire de recherche multi-critere contenant 4 criteres
class MultipleSearchBoxForm(forms.Form):
	crit_1 = forms.ChoiceField(choices=CRITERES_POSSIBLES)
	comp_1 = forms.ChoiceField(choices=COMPARATEURS_POSSIBLES)
	query_1 = forms.CharField(max_length=128)
	op_1 = forms.ChoiceField(choices=OPERATEURS_LOGIQUES)
	crit_2 = forms.ChoiceField(choices=CRITERES_POSSIBLES)
	comp_2 = forms.ChoiceField(choices=COMPARATEURS_POSSIBLES)
	query_2 = forms.CharField(max_length=128)
	op_2 = forms.ChoiceField(choices=OPERATEURS_LOGIQUES)
	crit_3 = forms.ChoiceField(choices=CRITERES_POSSIBLES)
	comp_3 = forms.ChoiceField(choices=COMPARATEURS_POSSIBLES)
	query_3 = forms.CharField(max_length=128)
	op_3 = forms.ChoiceField(choices=OPERATEURS_LOGIQUES)
	crit_4 = forms.ChoiceField(choices=CRITERES_POSSIBLES)
	comp_4 = forms.ChoiceField(choices=COMPARATEURS_POSSIBLES)
	query_4 = forms.CharField(max_length=128)

templates/recherche/affichage_page.html
{% extends "main.html" %}
{% load url from future %}
{% block main %}
	<div id="main">   
		<div class="yui3-g">
			<div class="yui3-u-1-5" id="col-left">
				<div id="search-box">
					<form action="/search" method="get">
						<input id="id_q" type="text" maxlength="128" name="q"/>
						<input type="submit" value="Submit" id="submit"/>
					</form>	
				</div>
			</div>
			<div class="yui3-u-3-5 page">
				<div id="search-result">
					<h2> {{ressource.titre}} </h2>
					{% if ressource.texte %}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{ressource.texte}} {% else %} <b> Aucun texte disponible </b> {% endif %}
					<br/><br/><b> Année: </b> 
					<a href="/search/?q={{ressource.annee}}">{{ressource.annee}}</a>,<br/>
					{% if ressource.page_deb and ressource.page_fin %} <b> Pages: </b> {{ ressource.page_deb }} à {{ressource.page_fin}}, <br/> {% endif %}
					{% if ressource.date_debut and ressource.date_fin %} <b> Date: </b> {% ifequal ressource.date_debut ressource.date_fin %} {{ressource.date_debut}} {% else %}  du {{ressource.date_debut}} au {{ressource.date_fin}}{% endifequal %}, <br/> {% endif %}					
					{% if ressource.editeur %}  <b> Editeur: </b> <a href="/search/?q={{ressource.editeur}}"> {{ressource.editeur}}</a>, <br/> {% endif %}
					{% if ressource.formation %} <b> Formation: </b> <a href="/search/?q={{ressource.formation}}"> {{ressource.formation}}</a>, <br/> {% endif %}
					{% if ressource.universite %} <b> Universite: </b> <a href="/search/?q={{ressource.universite}}">  Université {{ressource.universite}}</a>, <br/> {% endif %}
					{% if ressource.discipline %} <b> Discipline: </b> <a href="/search/?q={{ressource.discipline}}"> {{ressource.discipline}}</a>, <br/> {% endif %}
					{% if ressource.type_production %} <b> Type de production: </b> {{ressource.type_production}}, <br/> {% endif %}	
					{% if ressource.type_rapport %} <b> Type de Rapport: </b>  {{ressource.type_rapport}}, <br/> {% endif %}
					{% if revue.nom %}<b>{% for un_csc in ressource.ressourcecatsscat_set.all %} {% ifequal un_csc.id_sous_cat.slug 'colloques-seminaires' %} Colloque: {% else %} Revue: {% endifequal %}{% endfor %}</b>
					<i> <a href="/search/?q={{revue.nom}}">{{revue.nom}}</a></i>,<br/>{% endif %}
					<b> Auteur(s): </b>
					{% for un_auteur in auteurs %}
						<i> <a href="/search/?q={{un_auteur.nom}}">{{un_auteur.nom}} {{un_auteur.prenom}}</a></i>,
					{% endfor %}
					<br/>
					{% if tags %}
					<b> Tag(s): </b> 
					{% for un_tag in tags %}
						<i> <a href="/search/?q={{un_tag.nom}}">{{un_tag.nom}}</a></i>,
					{% endfor %}
					<br>
					{% endif %}
					<b> Type de publication: </b>
					{% for un_csc in cats_ss_cats %}
						<i> <a href="/search/?q={{un_csc.slug}}">{{un_csc.nom}}</a></i>,
					{% endfor %}
					</br/><br/>
					{% if ressource.lien_texte %}<h4><a href="{{ressource.lien_texte}}" target="_blank"> Texte complet ici </a> </h4> {% endif %}
					{% if request.toolbar.edit_mode %} <div class="modif"> <a href="{% url 'admin:opst_plugins_ressource_change' ressource.id %}" target="_blank"> <button> Modifier la ressource </button></a></div> {% endif %}
				</div>
			</div>
			<div class="yui3-u-1-5" id="col-right">       
			</div>
		</div>
	</div>
{% endblock %}

templates/recherche/recherche.html
{% comment %}
	Ce template permet l'affichage des resultats d'une recherche
{% endcomment %}
{# charge le module de pagination #}
{% load pagination_tags %}
{# charge le module de tri #}
{% load sorter_tags %}
{# l'importation de ce module permet de manipuler la fonction 'url' de la meme maniere que dans les dernieres versions de django #}
{% load url from future %}

<div id="search-result">
	{# L'affichage de variable envoyees par le plugin SearchResultPlugin se fait en ecrivant la variable a l'interieur des balises "{{ }}" #}
	<h2>{{results_n}} resultat{{ results_n|pluralize }} obtenu{{ results_n|pluralize }}{% if query_string %} pour "{{query_string}}"{% endif %}.</h2>
	
	{# Traitement des conditions et des boucles dans des balises "{% %}" #}
	{# s'il y a des resultats #}
	{% if results_n != 0 %}
	<div class="TableauResultat">
		<table>
			{# trie les resultats selon le parametre "sort" donne par l'url #}
			{% sort results as sorted_objects %}
			{# Ligne d'entete du tableau #}
			<tr>
				{# "ifequal" renvoie seulement si les deux chaines donnees sont identiques #}
				<td> Auteur(s) </td>
				<td> {% sortlink by 'titre' '-titre' %} Titre {% endsortlink %} {% ifequal sort '-titre' %}<i class="fa fa-sort-desc"></i> {% else %}{% ifequal sort 'titre' %} <i class="fa fa-sort-asc"></i> {% endifequal %}{% endifequal %} </td>
				<td> {% sortlink by 'texte' '-texte' %} Texte {% endsortlink %} {% ifequal sort '-texte' %}<i class="fa fa-sort-desc"></i> {% else %}{% ifequal sort 'texte' %} <i class="fa fa-sort-asc"></i> {% endifequal %}{% endifequal %} </td>
				<td> {% sortlink by 'annee' '-annee' %} Année{% endsortlink %} {% if not sort %} <i class="fa fa-sort-desc"></i> {% endif %} {% ifequal sort 'annee' %}<i class="fa fa-sort-asc"></i> {% else %}{% ifequal sort '-annee' %} <i class="fa fa-sort-desc"></i> {% endifequal %}{% endifequal %} </td>
				<td> Tag(s) </td>
				<td> Nature(s) </td>
				<td> Compléments </td>
			</tr>
			{# On delimite le nombre de resultats a 10 par pages #}
			{% autopaginate sorted_objects 10 %}
			{# Pour chaque ressource recupere dans la liste "results" on affiche une nouvelle ligne #}
			{% for une_ressource in sorted_objects %}
				<tr>
					<td> <div id="cadre">{% for un_auteur in une_ressource.auteurs.all %} <a href="/search/?q={{un_auteur.nom}}+{{un_auteur.prenom}}"> {{un_auteur.nom}} {{un_auteur.prenom}}.</a> <br/> {% empty %} Aucun auteur {% endfor %} </div> </td>
					<td> {% if une_ressource.lien_texte %}<div id="cadre"><a href="{{une_ressource.lien_texte}}" target="_blank"> {% endif %} {{une_ressource.titre}} </a> </div> </td>
					<td> {% if une_ressource.texte %} {{ une_ressource.texte|truncatewords:20 }} </div> {% else %} Aucun texte {% endif %} </td>
					<td> <a href="?q={{une_ressource.annee}}"> {{une_ressource.annee}}</a> </td>
					<td> {% if une_ressource.tags.all %}<div id="cadre">{% endif %}{% for un_tag in une_ressource.tags.all %} <a href="/search/?q={{un_tag.nom}}"> {{un_tag.nom}}</a> <br/> {% empty %} Aucun tag {% endfor %} </div> </td>
					<td> <div id="cadre">{% for une_nature in une_ressource.ressourcecatsscat_set.all %} <a href="/search/?q={{une_nature.id_sous_cat.nom}}"> {{une_nature.id_sous_cat.nom}}</a> {% empty %} Aucune nature {% endfor %} </div> </td>
					<td> <b> <a href="/opst_root/affichage/{{une_ressource.slug}}"> Plus d'infos </a> </b> </td>
				</tr>
			{% endfor %}
		</table>
	</div>
	<br/><br/>
	{% paginate %}
	{% endif %}
</div>